### ISSUE TITLE
parallel processing, speed of fitDM, issues with MGLM

### ISSUE THREAD

**Issue by parsifal9** [mcalgaro93/benchdamic#3]
Hi Matteo,
I have a question (or several) about DM. Sorry this is a bit long and discursive.
Lots of details below but basically I have had trouble running the DM models. I have not tried the
runMocks using it as I can't get fitDM to run to completion.

In addition
a) there are problems with MGLM. I have fixed some small bugs and have emailed the authors but have not heard from
them yet. However, the major problem seems to be that it ignores the options for parallel processing
b) I installed the development version of benchdamic (1.5.2). However the parallel extensions do not include the
function fitDM

So my question (finally) is are you getting DM to run on data sets of this size?
Do you see any way forward? 

Bye

1) the Dirichlet-Multinomial models are very slow. I have not managed to run this command. Killed it after many hours
```
> ps
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 26742 taxa and 800 samples ]
sample_data() Sample Data:       [ 800 samples by 16 sample variables ]
tax_table()   Taxonomy Table:    [ 26742 taxa by 7 taxonomic ranks ]
system.time(
DM_GOF_salmon_2017 <- fitModels(
    object = ps,
    models = c("DM"),
    scale_HURDLE = c("median", "default"),
    verbose = TRUE # TRUE is always suggested
)
)
```

4) MGLM::MGLMreg seems to ignore options to use multiple processors. MGLMmodified is my version with a couple of small bugs fixed
(needed "drop=FALSE" in one instance and referenced a non-existing "glm.private" in another). counts is just the sample_data from ps above.

```
library(MGLMmodified)
system.time(dmFit <- MGLMmodified::MGLMreg.fit(Y = counts[,1:1000], X = D, dist = "DM",  display = TRUE))
#OK 76.247   0.202  76.445 

library(parallel)
cl<-makeCluster(10)
system.time(dmFit <- MGLMmodified::MGLMreg.fit(Y = counts[,1:1000], X = D, dist = "DM",  display = TRUE,parallel=TRUE,cores=10,cl=cl))
#75.49 0.171 75.66
#it not not seem to be using the parallel cluster at all

system.time(dmFit <- MGLMmodified::MGLMreg.fit(Y = counts[,1:10000], X = D, dist = "DM",  display = TRUE,parallel=TRUE,cores=10,cl=cl))
[1] "Iteration 2 Newton's update, log-likelihood-1893842.17659691"
[1] "Iteration 3 Newton's update, log-likelihood-1738941.34109906"
[1] "Iteration 4 Newton's update, log-likelihood-1320853.59012173"
[1] "Iteration 5 Newton's update, log-likelihood-1310276.33876724"
[1] "Iteration 6 Newton's update, log-likelihood-1279677.8961476"
[1] "Iteration 7 Newton's update, log-likelihood-1271627.1313208"
[1] "Iteration 8 Newton's update, log-likelihood-1269623.06317947"
[1] "Iteration 9 Newton's update, log-likelihood-1269251.40475852"
[1] "Iteration 10 Newton's update, log-likelihood-1269217.60304696"
[1] "Iteration 11 Newton's update, log-likelihood-1269216.86744467"
#killed after 10 hours
```

**Comment by mcalgaro93** [comment]
Hi @parsifal9,
that is a very big dataset. Unfortunately, I don't know how the MGLM package is implemented underneath. I think there are 3 options available: 

1. to wait for the MGLM maintainers response;
2. to look for an alternative package able to fit a dirichlet-multinomial distribution in CRAN or Bioconductor;
3. to filter your dataset to reduce dimensionality. 

In the latter case you could proceed by agglomerating taxa to a specified taxonomical rank. I know this could lead you to a loss of information but you are not losing counts, the library sizes are remaining the same. Alternatively, you could decide to filter by prevalence your features, _e.g._, by keeping only those which are present in at least the 10% of the samples. Finally, if you are confident enough to say that all your 800 samples are homogeneous (check this with a beta-diversity analysis) you can choose a subgroup of them, as representative as possible, and perform the analysis only on those.

I'm sorry I can't be of more help.
Matteo

**Comment by parsifal9** [comment]
Hi Matteo,
Thanks for your help and advice.  This is what I have found so far:
1) there are a couple of small coding problems in MGLM but they have nothing to do with my problem.
    - the parallel section of the MGLM code is not even used in this problem
    - the problem is the amount of time spent in the function "hessian"
2) ALDEx2 fits the same model (as far as I can tell). However, it frequently runs into the problem that a matrix index can not be
   larger than 2^31-1. Hence the number of Monte Carlo samples has to be limited (less than the recommended values)
3) this appears to be the only viable option. 

I will close this issue now. 
Thanks Again
Bye
