### ISSUE TITLE
DA_ALDEx2

### ISSUE THREAD

**Issue by bylam** [mcalgaro93/benchdamic#7]
how to save the result DA_ALDEx2,. It seems that the results only include values such as we.ep and we.eBH, but do not provide the final result of the enriched group.

**Comment by mcalgaro93** [comment]
Dear @bylam. You should be able to find the whole ALDEx2 output on the `statInfo` slot of every output related to ALDEx2. 

Here is an example:
```
library(benchdamic)
library(phyloseq)
set.seed(1)
# Create a very simple phyloseq object
counts <- matrix(rnbinom(n = 300, size = 3, prob = 0.5), nrow = 50, ncol = 6)
metadata <- data.frame("Sample" = c("S1", "S2", "S3", "S4", "S5", "S6"),
                       "group" = as.factor(c("A", "A", "A", "B", "B", "B")))
ps <- phyloseq::phyloseq(phyloseq::otu_table(counts, taxa_are_rows = TRUE),
                         phyloseq::sample_data(metadata))
# Differential abundance with wilcox test and denom = "iqlr"
DA_w <- DA_ALDEx2(ps, design = "group", test = "wilcox", denom = "iqlr", 
    paired.test = FALSE, contrast = c("group", "B", "A"))

head(DA_t$statInfo)
```
The `effect` column contains the direction of the differential abundance.

Please, let me know if this answers your question.
Matteo
